name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build website
        run: npx nx run website:build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/apps/website
